name: Update flake
on:
  schedule:
    - cron: "0 0 * * *"
permissions:
  contents: write
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix --experimental-features 'nix-command flakes' flake update
      - name: commit & push
        run: |
          git config --global user.name 'z0al'
          git config --global user.email 'z0al@users.noreply.github.com'
          git add flake.lock
          git commit -m "chore(ci): update flake.lock" --allow-empty
          git push
